### ISSUE TITLE
numeric_suite_tutorial and graph_mode_static_quantization_tutorial fail on CI test

### ISSUE THREAD

**Issue by guyang3532** [pytorch/tutorials#1101]
The fail job link:
https://app.circleci.com/pipelines/github/pytorch/tutorials/2260/workflows/28fe0633-2d0d-49e8-aa42-b524ca2bfaac/jobs/39040

Traceback:
C:\Users\circleci\project\prototype_source\numeric_suite_tutorial.py failed leaving traceback:
Traceback (most recent call last):
  File "C:\tools\miniconda3\envs\testenv\lib\site-packages\sphinx_gallery\gen_rst.py", line 394, in _memory_usage
    out = func()
  File "C:\tools\miniconda3\envs\testenv\lib\site-packages\sphinx_gallery\gen_rst.py", line 382, in __call__
    exec(self.code, self.globals)
  File "C:\Users\circleci\project\prototype_source\numeric_suite_tutorial.py", line 86, in <module>
    print(key, compute_error(wt_compare_dict[key]['float'], wt_compare_dict[key]['quantized'].dequantize()))
  File "C:\Users\circleci\project\intermediate_source\memory_format_tutorial.py", line 260, in check_cl
    'Operator `{}` lost channels_last property'.format(name))
Exception: Operator `dequantize` lost channels_last property

C:\Users\circleci\project\prototype_source\graph_mode_static_quantization_tutorial.py failed leaving traceback:
Traceback (most recent call last):
  File "C:\tools\miniconda3\envs\testenv\lib\site-packages\sphinx_gallery\gen_rst.py", line 394, in _memory_usage
    out = func()
  File "C:\tools\miniconda3\envs\testenv\lib\site-packages\sphinx_gallery\gen_rst.py", line 382, in __call__
    exec(self.code, self.globals)
  File "C:\Users\circleci\project\prototype_source\graph_mode_static_quantization_tutorial.py", line 234, in <module>
    ts_model = torch.jit.script(float_model).eval() # ts_model = torch.jit.trace(float_model, input)
  File "C:\tools\miniconda3\envs\testenv\lib\site-packages\torch\jit\__init__.py", line 1516, in script
    return torch.jit._recursive.create_script_module(obj, torch.jit._recursive.infer_methods_to_compile)
  File "C:\tools\miniconda3\envs\testenv\lib\site-packages\torch\jit\_recursive.py", line 318, in create_script_module
    return create_script_module_impl(nn_module, concrete_type, stubs_fn)
  File "C:\tools\miniconda3\envs\testenv\lib\site-packages\torch\jit\_recursive.py", line 372, in create_script_module_impl
    script_module = torch.jit.RecursiveScriptModule._construct(cpp_module, init_fn)
  File "C:\tools\miniconda3\envs\testenv\lib\site-packages\torch\jit\__init__.py", line 1900, in _construct
    init_fn(script_module)
  File "C:\tools\miniconda3\envs\testenv\lib\site-packages\torch\jit\_recursive.py", line 353, in init_fn
    scripted = create_script_module_impl(orig_value, sub_concrete_type, infer_methods_to_compile)
  File "C:\tools\miniconda3\envs\testenv\lib\site-packages\torch\jit\_recursive.py", line 376, in create_script_module_impl
    create_methods_from_stubs(concrete_type, stubs)
  File "C:\tools\miniconda3\envs\testenv\lib\site-packages\torch\jit\_recursive.py", line 292, in create_methods_from_stubs
    concrete_type._create_methods(defs, rcbs, defaults)
  File "C:\tools\miniconda3\envs\testenv\lib\site-packages\torch\jit\_recursive.py", line 602, in compile_unbound_method
    create_methods_from_stubs(concrete_type, (stub,))
  File "C:\tools\miniconda3\envs\testenv\lib\site-packages\torch\jit\_recursive.py", line 292, in create_methods_from_stubs
    concrete_type._create_methods(defs, rcbs, defaults)
  File "C:\tools\miniconda3\envs\testenv\lib\site-packages\torch\jit\_recursive.py", line 583, in try_compile_fn
    return torch.jit.script(fn, _rcb=rcb)
  File "C:\tools\miniconda3\envs\testenv\lib\site-packages\torch\jit\__init__.py", line 1547, in script
    ast = get_jit_def(obj, obj.__name__)
  File "C:\tools\miniconda3\envs\testenv\lib\site-packages\torch\jit\frontend.py", line 185, in get_jit_def
    return build_def(ctx, fn_def, type_line, def_name, self_name=self_name)
  File "C:\tools\miniconda3\envs\testenv\lib\site-packages\torch\jit\frontend.py", line 207, in build_def
    param_list = build_param_list(ctx, py_def.args, self_name)
  File "C:\tools\miniconda3\envs\testenv\lib\site-packages\torch\jit\frontend.py", line 230, in build_param_list
    raise NotSupportedError(ctx_range, _vararg_kwarg_err)
torch.jit.frontend.NotSupportedError: Compiled functions can't take variable number of arguments or use keyword-only arguments with defaults:
  File "C:\Users\circleci\project\intermediate_source\memory_format_tutorial.py", line 240
    def check_cl(*args, **kwargs):
                         ~~~~~~~ <--- HERE
        was_cl = contains_cl(args)
        try:
'Conv2d._conv_forward' is being compiled since it was called from 'Conv2d.forward'
  File "C:\tools\miniconda3\envs\testenv\lib\site-packages\torch\nn\modules\conv.py", line 419
    def forward(self, input: Tensor) -> Tensor:
        return self._conv_forward(input, self.weight)

**Comment by guyang3532** [comment]
Fixed at https://github.com/pytorch/tutorials/pull/1105
