### ISSUE TITLE
RuntimeError: Cuda out of memory

### ISSUE THREAD

**Issue by keremtatlici** [pytorch/tutorials#1305]
I try to train my custom dataset and i get this error
`Epoch: [0]  [ 0/35]  eta: 0:02:27  lr: 0.000152  loss: 3.0681 (3.0681)  loss_classifier: 0.5868 (0.5868)  loss_box_reg: 0.8825 (0.8825)  loss_mask: 1.3281 (1.3281)  loss_objectness: 0.0910 (0.0910)  loss_rpn_box_reg: 0.1796 (0.1796)  time: 4.2090  data: 3.1654  max mem: 2559
Traceback (most recent call last):
  File "/home/shakabrah/keremWorkSpace/BalıkSayma/FishCounterWithMaskRCNN/train.py", line 189, in <module>
    train_one_epoch(model, optimizer, data_loader, device, epoch, print_freq=10)
  File "/home/shakabrah/keremWorkSpace/BalıkSayma/FishCounterWithMaskRCNN/engine.py", line 30, in train_one_epoch
    loss_dict = model(images, targets)
  File "/home/shakabrah/anaconda3/envs/fishcounter/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/shakabrah/anaconda3/envs/fishcounter/lib/python3.6/site-packages/torchvision/models/detection/generalized_rcnn.py", line 80, in forward
    images, targets = self.transform(images, targets)
  File "/home/shakabrah/anaconda3/envs/fishcounter/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/shakabrah/anaconda3/envs/fishcounter/lib/python3.6/site-packages/torchvision/models/detection/transform.py", line 105, in forward
    image, target_index = self.resize(image, target_index)
  File "/home/shakabrah/anaconda3/envs/fishcounter/lib/python3.6/site-packages/torchvision/models/detection/transform.py", line 147, in resize
    image, target = _resize_image_and_masks(image, size, float(self.max_size), target)
  File "/home/shakabrah/anaconda3/envs/fishcounter/lib/python3.6/site-packages/torchvision/models/detection/transform.py", line 53, in _resize_image_and_masks
    mask = F.interpolate(mask[:, None].float(), scale_factor=scale_factor)[:, 0].byte()
  File "/home/shakabrah/anaconda3/envs/fishcounter/lib/python3.6/site-packages/torch/nn/functional.py", line 3132, in interpolate
    return torch._C._nn.upsample_nearest2d(input, output_size, scale_factors)
RuntimeError: CUDA out of memory. Tried to allocate 1008.00 MiB (GPU 0; 3.95 GiB total capacity; 1.97 GiB already allocated; 217.38 MiB free; 2.61 GiB reserved in total by PyTorch)`

Someone in pytorch forum tell me to use torch.amp module but i don't know how can i configure that module to this colab project.And i am working on my local laptop not on google colab.

Any ideas ?

**Comment by MaxVanDijck** [comment]
The error is because you have ran out of memory on your GPU (CUDA out of memory). To solve this issue try to reduce your batch size.
