### ISSUE TITLE
Build failed 

### ISSUE THREAD

**Issue by kexul** [pytorch/tutorials#131]
# Sphinx version: 2.5.6
# Python version: 2.7.13 (CPython)
# Docutils version: 0.13.1 release
# Jinja2 version: 2.9.6
# Last messages:

# Loaded extensions:
Traceback (most recent call last):
  File "/home/xwy/anaconda2/lib/python2.7/site-packages/Sphinx-1.5.6-py2.7.egg/sphinx/cmdline.py", line 295, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/home/xwy/anaconda2/lib/python2.7/site-packages/Sphinx-1.5.6-py2.7.egg/sphinx/application.py", line 244, in __init__
    self._init_builder(self.buildername)
  File "/home/xwy/anaconda2/lib/python2.7/site-packages/Sphinx-1.5.6-py2.7.egg/sphinx/application.py", line 315, in _init_builder
    self.emit('builder-inited')
  File "/home/xwy/anaconda2/lib/python2.7/site-packages/Sphinx-1.5.6-py2.7.egg/sphinx/application.py", line 589, in emit
    results.append(callback(self, *args))
  File "/home/xwy/anaconda2/lib/python2.7/site-packages/sphinx_gallery/gen_gallery.py", line 237, in generate_gallery_rst
    seen_backrefs)
  File "/home/xwy/anaconda2/lib/python2.7/site-packages/sphinx_gallery/gen_rst.py", line 400, in generate_dir_rst
    this_entry = _thumbnail_div(build_target_dir, fname, intro) + """
  File "/home/xwy/anaconda2/lib/python2.7/site-packages/sphinx_gallery/backreferences.py", line 181, in _thumbnail_div
    thumbnail=thumb, ref_name=ref_name)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 74: ordinal not in range(128)
~                                                                                      
~                                                                                      
~                                                                                      
~                                                                                      
~                                                                                      
~                                                                                      
                                                                     7,19          All

**Comment by kexul** [comment]
Solved by setting the charset.

**Comment by d-li14** [comment]
@kexul Could you please describe your solution in detail? I ran into the same problem just now.

**Comment by kexul** [comment]
@d-li14 Add a sitecustomize.py file in your python site-package folder(such as /usr/lib/python2.7/site-packages/), and add the following string:
```
# encoding=utf8 
import sys

reload(sys) 
sys.setdefaultencoding('utf8')
```

It solved this problem, but I encountered segment fault when `make docs`, then I switched to `make html-noplot` and encountered `FileExistsError`, then I comment line 197 to line 182  in custom_directives.py, then I compiled it successfully. 
Hope it help!

**Comment by d-li14** [comment]
@kexul I also use the packages in Anaconda2. And thanks for your solution, it exactly works, but maybe a little typo error in your reply: "comment line **197** to line 182 in custom_directives.py, "
