### ISSUE TITLE
Chatbot tutorial - RuntimeError: 'lengths' argument should be a 1D CPU int64 tensor, but got 1D cuda:0 Long tensor

### ISSUE THREAD

**Issue by TheWorkingDeveloper** [pytorch/tutorials#1421]
Tried running this chatbot tutorial. Training goes well but when actually using the model by uncommenting the final line of code (as specified in the comments) it returns the following error:

`Iteration: 4000; Percent complete: 100.0%; Average loss: 2.4559
> hello?
Traceback (most recent call last):
  File "C:/Users/user/PycharmProjects/pytorch-tests/main.py", line 1377, in <module>
    evaluateInput(encoder, decoder, searcher, voc)
  File "C:/Users/user/PycharmProjects/pytorch-tests/main.py", line 1242, in evaluateInput
    output_words = evaluate(encoder, decoder, searcher, voc, input_sentence)
  File "C:/Users/user/PycharmProjects/pytorch-tests/main.py", line 1225, in evaluate
    tokens, scores = searcher(input_batch, lengths, max_length)
  File "C:\Users\user\.conda\envs\pytorch-tests\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:/Users/user/PycharmProjects/pytorch-tests/main.py", line 1160, in forward
    encoder_outputs, encoder_hidden = self.encoder(input_seq, input_length)
  File "C:\Users\user\.conda\envs\pytorch-tests\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:/Users/user/PycharmProjects/pytorch-tests/main.py", line 693, in forward
    packed = nn.utils.rnn.pack_padded_sequence(embedded, input_lengths)
  File "C:\Users\user\.conda\envs\pytorch-tests\lib\site-packages\torch\nn\utils\rnn.py", line 245, in pack_padded_sequence
    _VF._pack_padded_sequence(input, lengths, batch_first)
RuntimeError: 'lengths' argument should be a 1D CPU int64 tensor, but got 1D cuda:0 Long tensor

Process finished with exit code 1`

Unfamiliar with pytorch so no idea what the cause is or how to solve it, but it looks like something to do with tensor types.
Packages in environment:
![image](https://user-images.githubusercontent.com/33965786/111622596-af1d6100-87e9-11eb-9f51-783b80383287.png)

**Comment by svekars** [comment]
I was not able to reproduce the error against torch 2.0. If this is still an issue, please check against the latest PyTorch and provide detailed information about your environment. Closing for now.
