### ISSUE TITLE
using model(X).armax(1) error

### ISSUE THREAD

**Issue by b0r1ngx** [pytorch/tutorials#2122]
Hello there, I'm student of NN course, I'm try to implement FFNN (or TDNN) to work on prediction of AR(2)-model, im using PyTorch example, and on my data and NN architecture i got pred.argmax(1) - error:
```
Traceback (most recent call last):
  File "/home/b0r1ngx/PycharmProjects/ArtificialNeuroNets/group_00201/lab01/lab01_pytorch.py", line 116, in <module>
    first_method()
  File "/home/b0r1ngx/PycharmProjects/ArtificialNeuroNets/group_00201/lab01/lab01_pytorch.py", line 87, in first_method
    test(test_data, time_delay_nn, loss_function)
  File "/home/b0r1ngx/PycharmProjects/ArtificialNeuroNets/group_00201/lab01/lab01_pytorch.py", line 70, in test
    c1 = pred.argmax(1) == y_pred
IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)
```
where it's used in you're examples: 
here in test_loop function - https://github.com/pytorch/tutorials/blob/master/beginner_source/basics/optimization_tutorial.py

I'm also doesn't think that i get best `Hyperparameter`s / loss_function / optimizer - cos i get bad Accuracy / Avg loss in my case, 
please help me with that:
U can check my code here:
(now im using how its recommended -1 or 0, but there is always 0)
https://github.com/b0r1ngx/ArtificialNeuroNets/blob/master/group_00201/lab01/lab01_pytorch.py

Thanks!

**Comment by z-a-f** [comment]
Assuming your training data is `(y)`, and the prediction is `(y_pred)`, I am pretty sure it's supposed to be `c1 = y_pred.argmax(1) == y`.

**Comment by b0r1ngx** [comment]
> The link to your code returns 404. Can you please provide the correct link?

https://github.com/pytorch/tutorials/issues/2122#issuecomment-1337691296

**Comment by b0r1ngx** [comment]
Sorry that I am lost here, I just delete part of code that I got as a problem:|

**Comment by b0r1ngx** [comment]
> Assuming your training data is `(y)`, and the prediction is `(y_pred)`, maybe it's supposed to be `c1 = y_pred.argmax(1) == y`? Check your variable names.

Thanks. Ok I check it out and back here

**Comment by svekars** [comment]
@b0r1ngx were you able to test this? If no more questions/suggestions, can we mark this issue as resolved?
