### ISSUE TITLE
[BUG] - intermediate_source/torch_export_tutorial.py fails against 2.4 RC binaries

### ISSUE THREAD

**Issue by brycebortree** [pytorch/tutorials#2940]
### Add Link

https://pytorch.org/tutorials/intermediate/torch_export_tutorial.html

## The [intermediate_source/torch_export_tutorial.py](https://github.com/pytorch/tutorials/blob/main/intermediate_source/torch_export_tutorial.py) is failing with the following error message:

```
Unexpected failing examples:
2024-06-17T23:56:15.4845763Z /var/lib/workspace/intermediate_source/torch_export_tutorial.py failed leaving traceback:
2024-06-17T23:56:15.4846533Z Traceback (most recent call last):
2024-06-17T23:56:15.4847335Z   File "/var/lib/workspace/intermediate_source/torch_export_tutorial.py", line 208, in <module>
2024-06-17T23:56:15.4848156Z     bad2_nonstrict = export(Bad2(), (torch.randn(3, 3),), strict=False)
2024-06-17T23:56:15.4849146Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/export/__init__.py", line 174, in export
2024-06-17T23:56:15.4849883Z     return _export(
2024-06-17T23:56:15.4850608Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/export/_trace.py", line 945, in wrapper
2024-06-17T23:56:15.4851330Z     raise e
2024-06-17T23:56:15.4852033Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/export/_trace.py", line
```

[link to build](https://github.com/pytorch/tutorials/actions/runs/9521343224/job/26340454931?pr=2932)

### Describe your environment

* Pytorch version 2.4
* CUDA 12
* CI

cc @avikchaudhuri @gmagogsfm @zhxchen17 @tugsbayasgalan @angelayi @suo @ydwu4

**Comment by brycebortree** [comment]
@angelayi

**Comment by svekars** [comment]
@williamwen42 @zhxchen17

**Comment by angelayi** [comment]
@tugsbayasgalan this is a regression of having pre-dispatch export. Here is the test case: 
```
class Bad2(torch.nn.Module):
    def forward(self, x):
        x.data[0, 0] = 3
        return x

bad2_nonstrict = export(Bad2(), (torch.randn(3, 3),), strict=False)
```

**Comment by svekars** [comment]
This should have been fixed.
