### ISSUE TITLE
If I don't download data, error ocurr when defining model for char RNN classification

### ISSUE THREAD

**Issue by misogil0116** [pytorch/tutorials#334]
# Description
Hello, I got an error like #260, and I find that this error occur when I forgot downloading names data from [here](https://download.pytorch.org/tutorial/data.zip)

Error message is like this.

```
Traceback (most recent call last):
  File "classify_names.py", line 101, in <module>
    rnn = RNN(n_letters, n_hidden, n_categories)
  File "classify_names.py", line 86, in __init__
    self.i2o = nn.Linear(input_size + hidden_size, output_size)
  File "/home/nishimura/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/torch/nn/modules/linear.py", line 46, in __init__
    self.reset_parameters()
  File "/home/nishimura/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/torch/nn/modules/linear.py", line 49, in reset_parameters
    stdv = 1. / math.sqrt(self.weight.size(1))
RuntimeError: Dimension out of range (expected to be in range of [-1, 0], but got 1)
```

When I undertake [generating names with RNN tutorial](https://pytorch.org/tutorials/intermediate/char_rnn_generation_tutorial.html), I can find my error easily because there are an error exception when I forgot downloading training data.

So, I propose that this error exception may be written at classifying tutorial too.

**Comment by holly1238** [comment]
Text tutorials have been revamped since this issue was created
