### ISSUE TITLE
runtime_error observed with the example - Executing the Script Module in C++

### ISSUE THREAD

**Issue by deepali-c** [pytorch/tutorials#895]
I have observed the following error while executing the [Executing the Script Module in C++](https://pytorch.org/tutorials/advanced/cpp_export.html#step-4-executing-the-script-module-in-c)

```
$ ./example-app ../scripted_resnet_model.pt
ok
terminate called after throwing an instance of 'std::runtime_error'
  what():  matrix and vector expected, got 2D, 4D at <myenv>/work/aten/src/TH/generic/THTensorMath.cpp:287
The above operation failed in interpreter.
Traceback (most recent call last):
  File "script.py", line 10
    def forward(self, input):
        if input.sum() > 0:
          output = self.weight.mv(input)
                   ~~~~~~~~~~~~~~ <--- HERE
        else:
          output = self.weight + input
Serialized   File "code/__torch__.py", line 10
    _0 = torch.gt(torch.sum(input, dtype=None), 0)
    if bool(_0):
      output = torch.mv(self.weight, input)
               ~~~~~~~~ <--- HERE
    else:
      output = torch.add(self.weight, input, alpha=1)

Aborted
```

**Comment by holly1238** [comment]
Closing this as it is more than a year old. If this is still a problem for you, feel free to reopen this or open a new issue, thanks!
